### PR TITLE
Fix tunnelling on collision detection (closes #308)

### LINKED ISSUE #308: TrajectoryNode goes through a Collider if it can reach another one behind
If you use a TrajectoryNode with a probe and set the speed high enough, if there is two colliders in the same direction, the TrajectoryNode will go through the first collider to stick on the one behind it.
collider_goes_through

### PR DESCRIPTION
**Pull request by Darnagof**
Full speed ahead, no more tunneling :
image

Added magnitude function to UnitVector.

(+ added missing binding for getAllGameObjects proxy)

### CODE REVIEW

File: src/Core/Collision/PolygonalCollider.cpp [hunk 1]
```diff
@@ -104,25 +104,21 @@ namespace obe::Collision
...
         {
-            std::pair<double, Transform::UnitVector> minDist(-1, Transform::UnitVector());
-            for (auto& reachable : reachableColliders) {
-                double dist = std::sqrt(std::pow(reachable.second.x - destPos.x, 2)
-                    + std::pow(reachable.second.y - destPos.y, 2));
-                if (minDist.first == -1 || minDist.first > dist)
+            // Get lowest offset between this collider and a reachable collider
+            for (auto& reachable : reachableColliders)
+            {
+                if (reachable.second.magnitude() < collData.offset.to(Transform::Units::ScenePixels).magnitude())
```
Comment (Sygmei) [inline src/Core/Collision/PolygonalCollider.cpp:112]: Why do you need to convert to ScenePixels here ?

File: src/Core/Transform/UnitVector.cpp [hunk 2]
```diff
@@ -303,4 +303,8 @@ namespace obe::Transform
     {
         return std::sqrt(std::pow(x - vec.x, 2) + std::pow(y - vec.y, 2));
     }
+    double UnitVector::magnitude() const
+    {
+        return std::sqrt(std::pow(x, 2) + std::pow(y, 2));
```
Comment (Sygmei) [inline src/Core/Transform/UnitVector.cpp:308]: Maybe, it should use a standardized unit ?

File: src/Core/Collision/PolygonalCollider.cpp (hunk 1 above)
Comment (Darnagof) [reply src/Core/Collision/PolygonalCollider.cpp:112]: Because `getMaximumDistanceBeforeCollision(PolygonalCollider& collider, const Transform::UnitVector& offset)` return a vector in ScenePixels unit.

File: src/Core/Transform/UnitVector.cpp (hunk 2 above)
Comment (Darnagof) [reply src/Core/Transform/UnitVector.cpp:308]: Always returning the result in SceneUnits ?

Comment (Sygmei) [reply src/Core/Transform/UnitVector.cpp:308]: Yup for example, we can merge as-is for now since I'll have to do some refactor on UnitVector for v0.5 anyway, I'll modify the code later !

File: src/Core/Collision/PolygonalCollider.cpp (hunk 1 above)
Comment (Sygmei) [reply src/Core/Collision/PolygonalCollider.cpp:112]: Ah okay !

**Review by Sygmei — APPROVED** [review]
