### PR TITLE
throw exception on accessing an invalid event name

### LINKED ISSUE #415: No error message on EventGroup::trigger when using invalid event name
```lua
CustomGroup:trigger("invalid_name", { test = 3 })
```
Shows
```
 "invalid map<K, T> key"
```
without a meaningful error

### PR DESCRIPTION
**Pull request by PierrickLP**
close #415

### CODE REVIEW

File: include/Core/Event/EventGroup.hpp [hunk 1]
```diff
@@ -193,6 +193,11 @@ namespace obe::event
         {
             name = EventType::id;
         }
+        if(m_events.find(name) == m_events.end()) {
```
Comment (Sygmei) [inline include/Core/Event/EventGroup.hpp]: Please use proper coding convention
```cpp
if (...)
{
}
```
Also please use `contains` method

**Review by Sygmei — APPROVED** [review]
